### ISSUE TITLE
Add data

### ISSUE THREAD

**Issue by BoltzmannBrain** [numenta/NAB#132]
Below are the steps to adding more data during the Private Beta phase:

1. Select time-series data files to be added from several sources:
  - [x] customer data -- #71
  - [ ] time-series data from open databases -- #131
  - [ ] older data, ready to add -- #42 
  - [ ] data from outside contributors (specifically for NAB)
  - [ ] data from NuPIC -- #138
  - [x] add'l "mole" data -- #144
2. Label the datafiles -- #130
3. Run the label combiner, and add new datafiles to the repo
4. Run NAB without failure, update the [Scoreboard](https://github.com/numenta/NAB/wiki#nab-scoreboard)
5. Update documentation to reference the data sources

**Comment by breznak** [comment]
@BoltzmannBrain @rhyolight do you want to give me edit access? :no_entry: I cant edit someone else's issues here..

**Comment by breznak** [comment]
- [ ] Include [river-view](https://github.com/nupic-community/river-view/) datasets, @rhyolight can identify optimal candidates

**Comment by breznak** [comment]
- [ ] [Synthetic tests](https://github.com/numenta/NAB/issues/217)

**Comment by BoltzmannBrain** [comment]
@breznak thank you for the data ideas. We're specifically looking for data with labeled anomalies (this is tough!).

This issue is specific to v1.0, which we're finishing up now; i.e. all the data that will be included in v1.0 is already checked in. So w/ the v1.0 release (next week) we'll most likely close this issue and open a new one for adding data.

**Comment by rhyolight** [comment]
Would it help if there were a way to label anomalies in River View streams?

---------
Matt Taylor
OS Community Flag-Bearer
Numenta

**Comment by BoltzmannBrain** [comment]
Definitely, but only true anomalies (i.e. with a known cause), not labels as determined by an htm detector.

**Comment by rhyolight** [comment]
Yes, as in a way for river administrators to manually mark anomalies.

BTW, this would be an involved feature and I don't think I would attempt it
very soon.


---------
Matt Taylor
OS Community Flag-Bearer
Numenta

**Comment by BoltzmannBrain** [comment]
Are the administrators those whom add the stream to river view, or someone else?

And could you explain more why we wouldn't try this soon? Thanks Matt.



Sent from my Verizon Wireless 4G LTE smartphone


-------- Original message --------

**Comment by breznak** [comment]
> Would it help if there were a way to label anomalies in River View
streams?

Definitely! Not sure if for River, or better for NAB, but a visual tool for
human annotation of anomalies would be useful.
That's why I want to work on the plotter tool.

**Comment by breznak** [comment]
> @breznak thank you for the data ideas. We're specifically looking for data with labeled anomalies (this is tough!).

@BoltzmannBrain https://github.com/numenta/NAB/issues/212 has labeled anomalies; I'm planning to add it ASAP, though no rush to make it for v1.0 or not

**Comment by rhyolight** [comment]
> Are the administrators those whom add the stream to river view, or someone else?

I really don't know yet. This feature has not been designed. 
 
> And could you explain more why we wouldn't try this soon? Thanks Matt.

Because I don't have time. If someone else wants to try it, that would be fine with me.

**Comment by BoltzmannBrain** [comment]
Closing this issue b/c all the v1.0 data has been added. Potential data additions should have individual issues.
